---
title: "programacion_R"
author: "Roberto Vargas Castro"
date: "2024-05-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Fundamentos de programación - Aprende a programar desde cero (ATS).

  El presente archivo es una mezcla de los cursos "Fundamentos de programacion - Aprende a programar desde cero" de Alejandro Sanchez Taboada impartido en Udemy y el curso de "Analisis de datos con programcion en R" de Google impartido en Coursera. Se hace una union de los conceptos principales de la programacion de ambos cursos y se resuelven especificamente los ejercicios impartidos por Alejandro Sanchez Taboada.

## 1.- Elementos de entorno de Algoritmos y Programación.

### 1.1.- Información y procesamiento de la información.

  Antes de definir que es la Información y que es el procesamiento de la información, veamos unos conceptos:

* Una computadora es un procesador de datos y sistemas de procesamiento de información.
* Un sistema es un conjunto de componentes conectados interactivos que tienen un propósito y una unidad total.
* Un sistema de procesamiento de la información, es un sistema que transforma los datos brutos en información organizada significativa y útil.

  Para procesar la información son necesarias dos cosas:
  
* Hardware.- Es la parte fisica, lo tangible, lo que se puede tocar:

  - Unidad central de procesos (CPU): Conjunto de circuitos electrónicos capaces de ejecutar cálculos como operaciones lógicas y matemáticas.
  - Memoria central: La información procesadas por el CPU se almacena normalmente en la memoria central hasta que se terminan los cálculos.
  - Dispositivos de almacenamiento secundarios (Memoria auxiliar).
  - Periféricos o dispositivos de entrada/salida (E/S).
  
* Software.- Es la parte lógica, intangible, lo que no se puede tocar:

  - Es el conjunto de programas que controlan el funcionamiento del hardware de una computadora.

Definidos hardware y software damos paso a la definicion de Dato:

* El dato es una representación simbólica (númerica, alfabética, algorítmica, ect), un atributo o característica de una entidad. Los datos describen hechos empíricos, sucesos y entidades reales. Un dato puede ser un simple carácter, tal como 'a', un numero, o un dibujo, etc.

* Un dato e sla expresión general que describe los objetos con los cuales opera una computadora. Existem dos tipos de datos:

  - Simples (sin estrcutura):
    
    - Numéricos (enteros, reales).
    - Lógicos (boolean).
    - Carácter (char, string).
   
  - Compuestos (estructurados):
    
    - Registros.
    - Arreglos (vectores, matrices).
    - Archivos.
    
* Informacíon.- La información es un conjunto de datos acerca de algún suceso, hecho, fenómeno o situación, que organizados es un contexto determinado tienen su significado, cuyo propósito puede ser el de reducir la incertidumbre o incrementar el conocimiento acerca de algo.

* Procesamiento de la información.- La información se puede introducir en la computadora como entrada (input) y a continuación se procesan para producir una salida (output).

[Entrada (datos)] -> [Proceso] -> [Salida (resultado)]

 ### 1.2.- Algoritmo y Programa.

* Agoritmo.- Es un método para resolver un problema, es una secuencia ordenada de instrucciones que siempre se ejecutan en un tiempo finito, que describen el proceso que se debe seguir, para dar solución a un problema especifico.
  Siempre debe de haber un punto de inicio y un punto de terminación, estos deben ser únicos y deben ser fácilmente identificables.
  
  Características de un algortitmo:
  
* Tiene que ser preciso.
* Tiene que estar bien definido.
* Tiene que ser finito.
* Un algoritmo debe describir: Entrada, Proceso y Salida.

Por ejemplo: Convertir grados/minutos/segundos a grados en radianes.

* Inicio
* Entrada: ingresar los grados, minutos y segundos.
* A los grados sumarle los minutos entre 60 y los segundos entre   3600.
* Al resultado de la suma multiplicarlo por pi entre 180.
* Salida: imprimir los grados en radianes.
* Fin.

Tipos de algoritmos:

* Cualitativos.- Son aquellos en los que se describen los pasos utilizando palabras.

* Cuantitativos.- Son aquellos que se utilizan cálculos númericos para definir los pasos del proceso.

Lenguajes algorítmicos.- Es una serie de simbolos y reglas que se utilizan para describir de manera explicita un algoritmo, estos pueden ser:

  * Graficos.- Es la representacion gráfica de las operaciones que realiza un algoritmo. Por ejemplo: diagramas de flujo, diagramas N-S.
   
  * No gráficos.- Representa en forma descriptiva las operaciones que debe realizar un añgoritmo. Por ejemplo: Pseudocódigo.
  
* Programa.- Es el conjunto de instrucciones escritas en algún lenguaje de programación y que ejecutadas secuencialmente resuelven un problema especifico.

### 1.3.- Lenguaje de programación (parte 1).

¿Que es un lenguaje de programación?

  Es un conjunto de símbolos de reglas sintácticas y semánticas que definen su estructura y el significado de sus elementos y expresiones, y es utilizado para controlar el comportamiento físico y lógico de una maquina.

  Los lenguajes de programación tienen un conjunto de instrucciones que nos permiten realizar operaciones de entrada/salida, cálculos, manipulación de textos, lógica/comparación y almacenameinto/recuperacion.
  
Tipos de lenguaje de programación:

* Según el nivel de abstracción.

  - Lenguaje de máquina.
  
Las instrucciones en el lenguaje de máquina se expresan en términos de la unidad de memoria mas pequeña: el bit (dígito binario 0 o 1).
Ventaja: No necesita ser traducido, tiene una mayor adaptación al equipo.
Desventaja: La dificultad y lentitud en la codificación.
      
  - Lenguajes de bajo nivel.
  
Tambien llamado lenguaje ensamblador, se utilizan palabras mnemotécnicas (abreviaturas). Por ejemplo, mnemotécnicos típicos de operaciones aritméticas: ADD (sumar), SUB (restar), DIV (dividir), etc. Ejemplo:

ADD A, B C

"Suma (ADD) el número que tengas guardado en A mas el número que esta guardado en la posicion B y esa suma guardala en la posicion C".

Ventaja: no es tan dificíl como el lenguaje máquina.
Desventaja: cada máquina tiene su propio lenguaje, necesitamos un proceso de traducción.

  - Lenguajes de alto nivel.
  
Son aquellos en los que las instruccion o sentencia son escritas con palabras similiares a los lenguajes humanos (ingles), lo que facilita la escritura y comprensión del programa.

Ventaja: son independientes de cada máquina, los que los hace portables.
Desventaja: el proceso de traducción es muy largo y ocupa más recursos.

### 1.4.- Lenguaje de programación (parte 2).

* Según la forma de ejecución.

  - Lenguajes compilados.
  
  Se compilan una vez y se utilizan cuantas veces se desee sin necesidad de volver a utilizar el compilador.
  Los compiladores analizan todo el programa y no generan resultados si no es correcto todo el codigo.
  
  - Lenguajes interpretados.
  
  Son interpretados cada vez que se ejecutan y necesitan siempre del interprete.
  Los interpretes analizan las instrucciones segun las necesitan y pueden iniciar la ejecución de un programa con errores.

* Según el paradigma de programación.

  Un paradigma de programación representa un enfoque particular o filosofía para la construcción de un software. Tipos de paradigmas:
  
  - Algorítmico, imperativo o por procedimientos.
  
  Es el más común y está representado, por ejemplo por lenguajes de programación como C o BASIC.
  Describe la programación en términos del estado del programa y sentencias que cambian dicho estado. Los programas imperativos son un conjunto de instrucciones que le indican al computador cómo realizar una tarea.
  
  - Declarativo o predicativo.
  
  Basado en la utilización de predicados lógicos o funciones matemáticas, su objetivo es conseguir lenguajes expresivos en los que no sea necesario especificar como resolver el problema (programación convencional imperativa).
  
  - Lógico.
  
  El mecanismo de inferencia genérico se basa en los procedimientos de deducción de fórmulas válidas en un sistema axiomático.
  
  - Funcional.
  
  Representado por la familia de lenguajes LISP. El mecanismo de inferencia genérico se basa en la reproducción de una expresión funcional a otra equivalente simplificada.
  
  - Orientado a objetos.
  
  Cada vez más utilizado, sobre todo en combinación con el imperativo. De hecho los lenguajes orientados a objetos permiten la programación imperativa. Algunos ejemplos de lenguajes orientados son C++, Java, Python, etc. Usa objetos y sus interacciones para diseñar aplicaciones y programas de computadora. Esta basado en varias técnicas, incluyendo herencia, modularidad, polimorfismo y encapsulamiento.

### 1.5.- Metodologias para la solución de probelmas.

  Desde el punto de vista educativo, la solución de problemas mediante la proramación posibilita la activación de una amplia variedad de estilos de aprendizaje. Pueden encontrar diversas maneras de abordar problemas y plantear solciones.

  Es por ello que debemos de considerar cuaro fases, en escencia, para resolver problemas específicos mediante la programación de computadores.

1.- Analizar el problema.
2.- Diseñar el algoritmo.
3.- Traducir el algoritmo a un lenguaje de programación.
4.- Depurar el programa.

Definicion del problema:

  Esta fase está dada por el enunciado del problema, el cual requiere una definición clara y precisa. Es importante que se conozca lo que se desea que realice la computadora; mientras esto no se conozca del todo no tiene mucho caso continuar con la siguiente etapa.
  
Análisis del problema:

  Una vez que se ha comprendido lo que se desea de la computadora, es necesario definir:
  
  - Los datos de entrada.
  - Cuál es la informacion que se desea producir (salida).
  - Los métodos y fórmulas que se necesitan para procesar los datos.

Diseño del algoritmo:

  Las caracteristicas de un buen algoritmo son:
  
  - Debe tener un purto particular de inicio.
  - Debe ser preciso e indicar el orden de realización de cada paso.
  - Debe ser definido, no debe permitir dobles interpretaciones.
  - Debe ser general.
  - Debe ser finito en tamaño y en tiempo de ejecución.
  
Codificación:

  La codificación es la operación de escribir la solución del programa (de acuerdo a la lógica del diagrama de flujo o pseudocodigo), en una serie de instrucciones detalladas, en un código reconocible por la computadora, la serie de instrucciones detalladas se le conoce como código fuente, el cual se escribe en un. lenguaje de programación.
  
Prueba y depuración:

  Los errores humanos dentro de la programación de computadoras son muchos y aumentan considerablemente con la complejidad del problema. El proceso de identificar y eliminar errores, para dar paso a una solución sin errores se le llama depuración.
  
  La depuración o prueba resulta una tarea tan creativa como el mismo desarrollo de la solcuion, por ello se debe considerar con el mismo interes y entusiasmo.
  
Documentación:

  Es la guía o comunicación escrita en sus variadas formas, ya sea en enunciados, procedimiemtos, dibujos o diagramas.
  
  A menudi un prorama escrito por una persona, es usado por otra. Por ello la documentación sirve para ayudar a comprender o usar un programa o para facilitar futuras modificaciones (mantenimiento).
  
  La documentación se divide en tres partes:
  
  - La documentacion interna (comentarios en el codigo).
  - La docuemntación externa.
  - Manual de usuario.
  
Mantenimiento:

  Se lleva a cabo despues de terminado el programa, cuando se detecta que es necesario hacer algún cambio, ajuste o complementación al programa para que siga trabajando de manera correcta. Para poder realizar este trabajo se requiere que el programa este correctamente documentado.

## 2.- Entidades primitivas.

### 2.1.- Descargar e instalar PSeInt.

PSeInt es una herramienta para asistir a un estudiante en sus primeros pasos en prgramación. Medieante un simple e intuitivo pseudolenguaje en español (complementado con un editor de diagramas de flujo), le permite centrar su atención en los conceptos funamentales de la algoritmia computacional, minimizando las dificultades propias de un lenguaje y proporcionando un entorno de trabajo con numerosas ayudas y recursos didácticos.

- En google poner desvargar pseint y dar enter.
- Se selecciona el sistema operativo de la computadora.
- Se descarga y posteriormente se da doble click en el ejecutable.

### 2.2.- Identificadores (Constantes y Variables).

Identificador.- representa los datos de un programa (constante o variable). Un identificador es una cadena de caracteres que sirve para identificar una posicion en la memoria de la computadora, que nos permite accesar a su contenido.

entero (tipo de dato) numero (nombre del identificador);

Reglas para formar un identificador:

- La palabra debe comenzar con una letra (A-Z, mayusculas o minusculas) y no deben contener espacios en blanco.
- Letras, digitos y caracteres, pueden estar unidos por un caracter subrayado "_".
- El primer caracter no puede ser un numero.

Ejemplo:

letra
n_kilos
Resultado1
n_personas2

Tipos de identificadores:

- Constantes.- Es un dato numerico o alfanumerico que no cambia durante la ejecucion del programa.

Ejemplo:

PI = 3.1416

- Variables.- Es un espacio en la memoria de la computadora que permite almacenar temporalmente un dato durante la ejecucion de un proceso, su contenido puede cambiar durante la ejecucion del programa.

Ejemplo:

area = (base * altura) / 2

Clasificacion de las variables:

- Por su contenido:

  - Numericas
  - Lógicas
  - Alfanumericas (string)

- Por su uso:

  - De trabajo
  - Contadores
  - Acumuladores

### 2.3.- Tipos de Datos.

Los tipos de datos hacen referencia al tipo de información que se trabaja, todos los datos tienen un tipo aosciado. El tipo de dato determina la naturaleza del conjunto de valores que puede tomar una variable.

Clasificacion de los data types:

1.- Simples (sin estructura):
  1.1.- Númericos
  1.2.- Lógicos
  1.3.- Caracteres (char)
  
2.- Compuestos (estructurados, definidos por el usuario):
 
  2.1.- Simples o estáticos:
    2.1.1.- Arreglos (vectores, matrices)
    2.1.2.- Registros
    2.1.3.- Archivos.
    2.1.4.- Conjuntos
    2.1.5.- Cadenas de caracteres (string)
    
  2.2.- compuestos o dinamicos:
    2.2.1.- Punteros
    2.2.2.- Listas (pilas, colas)
    2.2.3.- Listas enlazadas
    2.2.4.- Arboles
    2.2.5.- Grafos

Pseudocodigo hecho en PSeInt:

Proceso principal
	
	Definir numero1 Como Entero;
	Definir numero2 Como Real;
	Definir misterio Como Logico;
	Definir letra Como Caracter;
	Definir palabra Como Cadena;
	
FinProceso

### 2.4.- Operación de asignación.

Consiste en atribuir un valor a una variabe:

  nombre_de_la_variable <- expresion
  
En algunos lenguajes de programacion, el simbolo puede variar a:

" = ", " := "

El proceso de asignacion se realiza en dos fases:

  num = 10;
  
1.- Se evalua la expresion de la parte derecha de la asignacion obteniendose un unico valor.

2.- Se asigna ese valor a la variable de la parte izquierda, sustituyendose el valor que tenia amteriormente.

¿Que es lo que hay que tener en cuenta?

  * En la parte izquierda solo puede haber una variable.
  * La variable a la que se le asigna el valor pierde su valor anterior.
  * El tipo de dato del valor que se obtiene al evaluar la parte derecha tiene que ser el mismo que el tipo de dato de la variable de parte izquierda, es decir una variable solo se le pueden dar valores de su mismo tipo de dato.

// Operación de asignación

Proceso principal
	
	Definir numero1 Como Entero; // La variable numero1 es entera
	Definir numero2 Como Real;
	Definir misterio Como Logico;
	Definir letra Como Caracter;
	Definir palabra Como Cadena;
	
	numero1 <- 11;
	numero2 <- 11.11;
	misterio <- verdadero;
	letra <- 'r';
	palabra <- "Hola";
	
FinProceso
